# Copyright The SfM Tool Authors
# SPDX-License-Identifier: Apache-2.0

site_name: SfM Tool
site_description: Fun with Structure from Motion
repo_url: https://github.com/sfmtool/sfmtool
repo_name: sfmtool/sfmtool

theme:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md
