# Copyright The SfM Tool Authors
# SPDX-License-Identifier: Apache-2.0

[workspace]
authors = ["Mark <399551+mwiebe@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "sfmtool"
platforms = ["win-64", "linux-64"]
version = "0.1"

[dependencies]
python = ">=3.13,<3.15"
rust = ">=1.85"

[pypi-dependencies]
sfmtool = { path = ".", editable = true }

[tasks]
gui = "cargo run --release --bin sfm-explorer"

[feature.test.tasks]
test = "pytest"
fmt = "ruff format src tests"
check = "ruff check src tests"

[feature.dev.tasks]
ipython = "ipython"

[feature.docs.pypi-dependencies]
zensical = "*"

[feature.docs.tasks]
docs-serve = "zensical serve"
docs-build = "zensical build"

[environments]
default = {solve-group = "default"}
test = {features = ["test"], solve-group = "default"}
dev = {features = ["dev"], solve-group = "default"}
docs = {features = ["docs"], solve-group = "default"}
