// Copyright The SfM Tool Authors
// SPDX-License-Identifier: Apache-2.0

use super::*;

#[test]
fn affine_fit_recovers_known_affine() {
    // A 3-corner fit of points generated by a known affine recovers it
    // exactly, and composing the map with its inverse is the identity (the
    // φ a same-orientation candidate sees → a no-op resample).
    let r = 16u32;
    let d = (r - 1) as f64;
    let (a, b, c, dd, e, f) = (1.3, -0.2, 4.0, 0.1, 0.9, -3.0);
    let grid = [(0.0, 0.0), (d, 0.0), (0.0, d), (d, d)];
    let mut pts = [(0.0, 0.0); 4];
    for (k, &(gx, gy)) in grid.iter().enumerate() {
        pts[k] = (a * gx + b * gy + c, dd * gx + e * gy + f);
    }
    let m = affine_grid_to_img(&pts, r);
    let got = [
        m[(0, 0)],
        m[(0, 1)],
        m[(0, 2)],
        m[(1, 0)],
        m[(1, 1)],
        m[(1, 2)],
    ];
    for (g, w) in got.iter().zip(&[a, b, c, dd, e, f]) {
        assert!((g - w).abs() < 1e-9, "{g} vs {w}");
    }
    let id = m.try_inverse().unwrap() * m;
    for i in 0..3 {
        for j in 0..3 {
            let want = if i == j { 1.0 } else { 0.0 };
            assert!((id[(i, j)] - want).abs() < 1e-9);
        }
    }
}

#[test]
fn pad_replicate_borders_and_center() {
    let rb = 3usize;
    let src: Vec<u32> = (0..9).collect();
    let guard = 2usize;
    let w = rb + 2 * guard;
    let p = pad_replicate(&src, rb, guard);
    // Interior maps back to the source; the border replicates the nearest edge.
    assert_eq!(p[guard * w + guard], src[0]); // (g,g) -> src(0,0)
    assert_eq!(p[(guard + 1) * w + (guard + 1)], src[rb + 1]); // -> src(1,1)
    assert_eq!(p[0], src[0]); // top-left corner replicates src(0,0)
    assert_eq!(p[w * w - 1], src[rb * rb - 1]); // bottom-right replicates src(2,2)
}

/// A synthetic padded base + scattered support, for the kernel tests/bench.
fn synthetic_base(rb: usize) -> FrontoBase {
    let guard = FRONTO_GUARD as usize;
    let bw = rb + 2 * guard;
    let patch: Vec<u32> = (0..bw * bw)
        .map(|k| {
            let r = (k * 7) % 256;
            let g = (k * 13 + 5) % 256;
            let b = (k * 29 + 11) % 256;
            (r | (g << 8) | (b << 16)) as u32
        })
        .collect();
    FrontoBase {
        patch,
        bw_pad: bw as u32,
        a0_inv: SMatrix::identity(),
        center_offset: Vector3::zeros(),
    }
}

fn synthetic_support(rb: usize) -> (Vec<i32>, Vec<i32>) {
    // 173 support pixels (not a multiple of 8, so the AVX2 tail is exercised).
    let mut cols = Vec::new();
    let mut rows = Vec::new();
    for k in 0..173 {
        cols.push((k % rb) as i32);
        rows.push((k * 3 % rb) as i32);
    }
    (cols, rows)
}

#[test]
fn resample_avx2_matches_scalar() {
    let rb = 24usize;
    let base = synthetic_base(rb);
    let (cols, rows) = synthetic_support(rb);
    let n = cols.len();
    // A few affine maps incl. one that pushes some pixels off the base edge
    // (exercises the clamp); the dispatcher picks AVX2 where available.
    for phi in [
        [1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
        [1.07, 0.04, 1.5, -0.03, 0.96, -0.8],
        [1.6, 0.2, 6.0, -0.25, 1.55, -5.0],
    ] {
        let p32 = [
            phi[0] as f32,
            phi[1] as f32,
            phi[2] as f32,
            phi[3] as f32,
            phi[4] as f32,
            phi[5] as f32,
        ];
        let mut want = vec![0f32; n * 3];
        resample_support_scalar(&base, &p32, &cols, &rows, 0, n, &mut want);
        let mut got = vec![0f32; n * 3];
        resample_support(&base, &phi, &cols, &rows, &mut got);
        for (a, b) in want.iter().zip(&got) {
            assert!((a - b).abs() < 5e-3, "{a} vs {b}");
        }
    }
}

/// On-demand micro-benchmark: `cargo test -p sfmtool-core resample_bench
/// -- --ignored --nocapture`. Times the dispatched (AVX2) kernel vs the
/// scalar reference on a 32×32-ish support.
#[test]
#[ignore]
fn resample_bench() {
    use std::time::Instant;
    let rb = 64usize;
    let base = synthetic_base(rb);
    let mut cols: Vec<i32> = Vec::new();
    let mut rows: Vec<i32> = Vec::new();
    for k in 0..812 {
        cols.push(k % 32);
        rows.push(k / 32 % 32);
    }
    let n = cols.len();
    let phi = [1.05, 0.03, 2.0, -0.02, 0.98, 1.5];
    let p32 = [
        phi[0] as f32,
        phi[1] as f32,
        phi[2] as f32,
        phi[3] as f32,
        phi[4] as f32,
        phi[5] as f32,
    ];
    let iters = 200_000;
    let mut out = vec![0f32; n * 3];
    let t = Instant::now();
    for _ in 0..iters {
        resample_support_scalar(&base, &p32, &cols, &rows, 0, n, &mut out);
        std::hint::black_box(&out);
    }
    let scalar = t.elapsed().as_nanos() as f64 / iters as f64;
    let t = Instant::now();
    for _ in 0..iters {
        resample_support(&base, &phi, &cols, &rows, &mut out);
        std::hint::black_box(&out);
    }
    let dispatch = t.elapsed().as_nanos() as f64 / iters as f64;
    println!(
        "resample {n} support px: scalar {scalar:.0} ns, dispatch {dispatch:.0} ns ({:.2}x)",
        scalar / dispatch
    );
}
