# Copyright The SfM Tool Authors
# SPDX-License-Identifier: Apache-2.0

"""Tests for the rotation-locked resection Rust binding
(``sfmtool._sfmtool.geometry.resect_translation``; see
``specs/core/rotation-locked-resection.md``).

Canonical camera convention throughout: the camera looks along −Z, so an
in-front point has ``z < 0`` in camera frame. Scenes are generated by
projecting camera-frame points through ``CameraIntrinsics.ray_to_pixel_batch``
(the same forward model the trim gate uses), with the world-to-camera rotation
held fixed and only the translation to recover.
"""

import numpy as np
import numpy.testing as npt
import pytest

from sfmtool._sfmtool.geometry import CameraIntrinsics, resect_translation


def _pinhole(f=500.0, w=640, h=480):
    return CameraIntrinsics.from_dict(
        {
            "model": "SIMPLE_PINHOLE",
            "width": w,
            "height": h,
            "parameters": {
                "focal_length": f,
                "principal_point_x": w / 2.0,
                "principal_point_y": h / 2.0,
            },
        }
    )


def _fisheye(f=300.0, w=640, h=480):
    return CameraIntrinsics.from_dict(
        {
            "model": "SIMPLE_RADIAL_FISHEYE",
            "width": w,
            "height": h,
            "parameters": {
                "focal_length": f,
                "principal_point_x": w / 2.0,
                "principal_point_y": h / 2.0,
                "radial_distortion_k1": 0.05,
            },
        }
    )


def _rotvec_to_quat_wxyz(v):
    theta = np.linalg.norm(v)
    if theta < 1e-12:
        return np.array([1.0, 0.0, 0.0, 0.0])
    axis = v / theta
    return np.array([np.cos(theta / 2), *(np.sin(theta / 2) * axis)])


def _quat_wxyz_to_matrix(q):
    w, x, y, z = q / np.linalg.norm(q)
    return np.array(
        [
            [1 - 2 * (y * y + z * z), 2 * (x * y - w * z), 2 * (x * z + w * y)],
            [2 * (x * y + w * z), 1 - 2 * (x * x + z * z), 2 * (y * z - w * x)],
            [2 * (x * z - w * y), 2 * (y * z + w * x), 1 - 2 * (x * x + y * y)],
        ]
    )


def _scene(cam, quat_wxyz, t_true, n=30, seed=3):
    """World points in front of the rotated camera and their exact pixels."""
    rng = np.random.default_rng(seed)
    r = _quat_wxyz_to_matrix(quat_wxyz)
    world = rng.uniform(-2, 2, size=(n, 3))
    world[:, 2] = rng.uniform(-8, -4, size=n)
    cam_pts = world @ r.T + t_true
    front = cam_pts[:, 2] < -0.5
    world, cam_pts = world[front], cam_pts[front]
    uv = cam.ray_to_pixel_batch(np.ascontiguousarray(cam_pts))
    return world, uv


_QUAT = _rotvec_to_quat_wxyz(np.array([0.15, -0.1, 0.05]))
_T_TRUE = np.array([0.4, -0.25, 0.3])


@pytest.mark.parametrize("make_cam", [_pinhole, _fisheye])
def test_exact_recovery(make_cam):
    cam = make_cam()
    world, uv = _scene(cam, _QUAT, _T_TRUE)
    out = resect_translation(cam, _QUAT, world, uv)
    assert out is not None
    npt.assert_allclose(np.asarray(out["translation"]), _T_TRUE, atol=1e-6)
    assert out["inliers"].dtype == bool
    assert out["inliers"].shape == (len(world),)
    assert out["inliers"].all()
    assert out["residual_norms"].shape == (len(world),)
    assert (np.asarray(out["residual_norms"]) < 1e-4).all()


def test_outlier_trimming_identifies_planted_outliers():
    cam = _pinhole()
    world, uv = _scene(cam, _QUAT, _T_TRUE, n=48, seed=5)
    uv = np.asarray(uv).copy()
    n = len(world)
    # ~10% stragglers with alternating offset directions — the largely
    # correct regime the trimmed gate is specified for.
    bad = np.arange(0, n, 10)
    signs = np.where((bad // 10) % 2 == 0, 1.0, -1.0)
    uv[bad, 0] += signs * 70.0
    uv[bad, 1] -= signs * 55.0
    out = resect_translation(cam, _QUAT, world, uv)
    assert out is not None
    npt.assert_allclose(np.asarray(out["translation"]), _T_TRUE, atol=1e-6)
    expected = np.ones(n, dtype=bool)
    expected[bad] = False
    npt.assert_array_equal(out["inliers"], expected)


def test_behind_camera_point_excluded():
    cam = _pinhole()
    world, uv = _scene(cam, _QUAT, _T_TRUE)
    r = _quat_wxyz_to_matrix(_QUAT)
    behind_cam = np.array([0.1, -0.2, 3.0])  # z > 0: behind the camera
    behind_world = r.T @ (behind_cam - _T_TRUE)
    world = np.vstack([world, behind_world])
    uv = np.vstack([uv, [300.0, 250.0]])
    out = resect_translation(cam, _QUAT, world, uv)
    assert out is not None
    assert not out["inliers"][-1]
    assert out["residual_norms"][-1] == 1e6
    npt.assert_allclose(np.asarray(out["translation"]), _T_TRUE, atol=1e-6)


def test_none_below_min_inliers():
    cam = _pinhole()
    world, uv = _scene(cam, _QUAT, _T_TRUE, n=8, seed=7)
    assert len(world) < 10
    assert resect_translation(cam, _QUAT, world, uv) is None
    # An explicit floor above the observation count also fails.
    world, uv = _scene(cam, _QUAT, _T_TRUE, n=30, seed=7)
    assert resect_translation(cam, _QUAT, world, uv, min_inliers=len(world) + 1) is None


def test_fortran_order_inputs_match_c_order():
    # A Fortran-ordered 2-D array must be read identically to C order.
    cam = _pinhole()
    world, uv = _scene(cam, _QUAT, _T_TRUE)
    c = resect_translation(cam, _QUAT, world, uv)
    f = resect_translation(cam, _QUAT, np.asfortranarray(world), np.asfortranarray(uv))
    assert c is not None and f is not None
    npt.assert_array_equal(c["translation"], f["translation"])
    npt.assert_array_equal(c["inliers"], f["inliers"])
    npt.assert_array_equal(c["residual_norms"], f["residual_norms"])


def test_shape_validation():
    cam = _pinhole()
    world, uv = _scene(cam, _QUAT, _T_TRUE)
    with pytest.raises(ValueError):
        resect_translation(cam, _QUAT, world[:, :2], uv)
    with pytest.raises(ValueError):
        resect_translation(cam, _QUAT, world, np.asarray(uv)[:, :1])
    with pytest.raises(ValueError):
        resect_translation(cam, _QUAT, world[:-1], uv)
